### ISSUE TITLE
Some videos can't be played

### ISSUE THREAD

**Issue by zarianu** [andy-g/kodi.plugin.video.redbulltv2#8]
Hello,

trying to follow Dakar 2018 using this plugin and got strange error on some videos (others play nicely though).

I'm using LibreELEC 8.2.2 on Raspberry Pi3, Kodi 17.6 and the last version of your plugin available in repos - 2.0.1.

Here's the debug log:

> 08:34:55.383 T:1945133056   DEBUG: LIRC: Update - NEW at 35134521:161 0 KEY_SELECT devinput (KEY_SELECT)
> 08:34:55.383 T:1945133056   DEBUG: OnKey: 11 (0x0b, obc244) pressed, action is Select
> 08:34:55.405 T:1945133056   DEBUG: OnPlayMedia plugin://plugin.video.redbull.tv/?api_url=aHR0cHM6Ly9hcHBsZXR2LnJlZGJ1bGwudHYvY29udGVudC9BUC0xVFFHR1dXRzkxVzExP2NvbGxl%0AY3Rpb25faWQ9QVAtMVRQR0tSSlVEMjExMSUzQWxpdmVfcHJvZ3JhbXMmcGxheWxpc3RfcGF0aD1w%0AbGF5bGlzdHMlMkZBUC0xVFBHS1JKVUQyMTExJTNBbGl2ZV9wcm9ncmFtcyUzRnRvdGFsJTNEMTYl%0AMjZsaW1pdCUzRDIwJTI2b2Zmc2V0JTNEMA%3D%3D%0A
> 08:34:55.405 T:1945129888   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
> 08:34:55.405 T:1945129888   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
> 08:34:55.410 T:1945133056   DEBUG: StartScript - calling plugin Red Bull TV('plugin://plugin.video.redbull.tv/','46','?api_url=aHR0cHM6Ly9hcHBsZXR2LnJlZGJ1bGwudHYvY29udGVudC9BUC0xVFFHR1dXRzkxVzExP2NvbGxl%0AY3Rpb25faWQ9QVAtMVRQR0tSSlVEMjExMSUzQWxpdmVfcHJvZ3JhbXMmcGxheWxpc3RfcGF0aD1w%0AbGF5bGlzdHMlMkZBUC0xVFBHS1JKVUQyMTExJTNBbGl2ZV9wcm9ncmFtcyUzRnRvdGFsJTNEMTYl%0AMjZsaW1pdCUzRDIwJTI2b2Zmc2V0JTNEMA%3D%3D%0A')
> 08:34:55.410 T:1416094624   DEBUG: Thread LanguageInvoker start, auto delete: false
> 08:34:55.410 T:1416094624    INFO: initializing python engine.
> 08:34:55.411 T:1416094624   DEBUG: CPythonInvoker(59, /storage/.kodi/addons/plugin.video.redbull.tv/default.py): start processing
> 08:34:55.428 T:1945129888   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
> 08:34:55.428 T:1945129888   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
> 08:34:55.431 T:1488974752   DEBUG: Thread scriptobs start, auto delete: false
> 08:34:55.466 T:1416094624   DEBUG: -->Python Interpreter Initialized<--
> 08:34:55.467 T:1416094624   DEBUG: CPythonInvoker(59, /storage/.kodi/addons/plugin.video.redbull.tv/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.redbull.tv/default.py"
> 08:34:55.467 T:1416094624   DEBUG: CPythonInvoker(59, /storage/.kodi/addons/plugin.video.redbull.tv/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.redbull.tv:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
> 08:34:55.467 T:1416094624   DEBUG: CPythonInvoker(59, /storage/.kodi/addons/plugin.video.redbull.tv/default.py): entering source directory /storage/.kodi/addons/plugin.video.redbull.tv
> 08:34:55.467 T:1416094624   DEBUG: CPythonInvoker(59, /storage/.kodi/addons/plugin.video.redbull.tv/default.py): instantiating addon using automatically obtained id of "plugin.video.redbull.tv" dependent on version 2.25.0 of the xbmc.python api
> 08:34:55.631 T:1945133056   DEBUG: ------ Window Init (DialogBusy.xml) ------
> 08:34:59.671 T:1416094624    INFO: CPythonInvoker(59, /storage/.kodi/addons/plugin.video.redbull.tv/default.py): script successfully run
> 08:34:59.679 T:1416094624    INFO: Python script stopped
> 08:34:59.680 T:1416094624   DEBUG: Thread LanguageInvoker 1416094624 terminating
> 08:34:59.680 T:1488974752   DEBUG: Thread scriptobs 1488974752 terminating
> 08:34:59.690 T:1945133056   DEBUG: Loading settings for master_6660.m3u8
> 08:34:59.700 T:1945133056   DEBUG: CPlayerCoreFactory::GetPlayers(master_6660.m3u8)
> 08:34:59.700 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
> 08:34:59.700 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
> 08:34:59.700 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
> 08:34:59.700 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
> 08:34:59.701 T:1945133056   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
> 08:34:59.701 T:1945133056   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
> 08:34:59.701 T:1945133056   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
> 08:34:59.701 T:1945133056   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
> 08:34:59.701 T:1945133056   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
> 08:34:59.701 T:1945133056   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
> 08:34:59.705 T:1945133056   DEBUG: Radio UECP (RDS) Processor - new CDVDRadioRDSData
> 08:34:59.705 T:1945133056  NOTICE: VideoPlayer: Opening: master_6660.m3u8
> 08:34:59.705 T:1945133056 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
> 08:34:59.705 T:1945133056   DEBUG: CMMALRenderer::CMMALRenderer
> 08:34:59.705 T:1945133056   DEBUG: CMMALRenderer::UnInitMMAL
> 08:34:59.705 T:1945133056   DEBUG: CMMALRenderer::PreInit
> 08:34:59.706 T:1488974752   DEBUG: Thread MMALProcess start, auto delete: false
> 08:34:59.706 T:1488974752   DEBUG: CMMALRenderer::Run - starting
> 08:34:59.706 T:1416094624   DEBUG: Thread VideoPlayer start, auto delete: false
> 08:34:59.706 T:1416094624  NOTICE: Creating InputStream
> 08:34:59.706 T:1416094624   DEBUG: CFileCache::Open - opening <master_6660.m3u8> using cache
> 08:34:59.706 T:1416094624   ERROR: Open - failed to open source <master_6660.m3u8>
> 08:34:59.706 T:1416094624   ERROR: CVideoPlayer::OpenInputStream - error opening [master_6660.m3u8]
> 08:34:59.706 T:1416094624  NOTICE: CVideoPlayer::OnExit()
> 08:34:59.707 T:1416094624   DEBUG: OnPlayBackStopped: play state was 1, starting 1
> 08:34:59.707 T:1416094624   DEBUG: Thread VideoPlayer 1416094624 terminating
> 08:34:59.707 T:1945133056   DEBUG: OnPlayBackStopped: play state was 3, starting 0
> 08:34:59.707 T:1945133056   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.redbull.tv/?api_url=aHR0cHM6Ly9hcHBsZXR2LnJlZGJ1bGwudHYvY29udGVudC9BUC0xVFFHR1dXRzkxVzExP2NvbGxl%0AY3Rpb25faWQ9QVAtMVRQR0tSSlVEMjExMSUzQWxpdmVfcHJvZ3JhbXMmcGxheWxpc3RfcGF0aD1w%0AbGF5bGlzdHMlMkZBUC0xVFBHS1JKVUQyMTExJTNBbGl2ZV9wcm9ncmFtcyUzRnRvdGFsJTNEMTYl%0AMjZsaW1pdCUzRDIwJTI2b2Zmc2V0JTNEMA%3D%3D%0A]
> 08:34:59.707 T:1945133056   DEBUG: Playlist Player: one or more items failed to play... aborting playback
> 08:34:59.707 T:1945133056   DEBUG: ------ Window Init (DialogConfirm.xml) ------
> 08:34:59.708 T:1945133056  NOTICE: CVideoPlayer::CloseFile()
> 08:34:59.708 T:1945133056  NOTICE: VideoPlayer: waiting for threads to exit
> 08:34:59.708 T:1945133056  NOTICE: VideoPlayer: finished waiting
> 08:34:59.708 T:1945133056   DEBUG: DeleteRenderer - deleting renderer
> 08:34:59.708 T:1945133056   DEBUG: CMMALRenderer::~CMMALRenderer
> 08:34:59.708 T:1945133056   DEBUG: CMMALRenderer::UnInitMMAL
> 08:34:59.708 T:1488974752   DEBUG: CMMALRenderer::Run - stopping
> 08:34:59.708 T:1488974752   DEBUG: Thread MMALProcess 1488974752 terminating
> 08:34:59.708 T:1945133056  NOTICE: CVideoPlayer::CloseFile()
> 08:34:59.708 T:1945133056  NOTICE: VideoPlayer: waiting for threads to exit
> 08:34:59.708 T:1945133056  NOTICE: VideoPlayer: finished waiting
> 08:34:59.711 T:1945133056   DEBUG: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
> 08:34:59.718 T:1945129888   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
> 08:34:59.718 T:1945129888   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
> 08:34:59.940 T:1945133056   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
> 
> 

Ready to do testing and to submit additional info as needed.

Thank you for your effort creating this add-on.

**Comment by andy-g** [comment]
Thanks for raising this, it seems to be using a different playlist format on this items compared to what I've seen before:

## What this stream is returning:

A base64 decode of that api_url in your log maps to https://appletv.redbull.tv/content/AP-1TQGGWWG91W11 (ignore everything after the `?`). Following that url, you can see that the `media_url` node points to a playlist:
https://dms.redbull.tv/v3/AP-1TQGGWWG91W11/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2IiwiY291bnRyeV9jb2RlIjoiemEiLCJleHBpcmVzIjoiMjAxOC0wMS0xMlQxMzoyMDo0My4xODkyNTkzMDNaIiwib3NfZmFtaWx5IjoidHZtbCIsInJlbW90ZV9pcCI6IjU0LjE2Ni4xNjcuMTkwIiwidWEiOiJSdWJ5IiwidWlkIjoiY2EyZGIyMzMtYjU0Zi00NTMwLWE3MjQtNGMyYTY0NGJjYjA1In0.NLaht0uVhNqL-JIEJdgXv-a0BWkko66irYuixR98ysA/playlist.m3u8 which contains the stream info, but doesn't include a full url, unlike all the other stream playlists I've seen the redbull tv use before:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=290400,AVERAGE-BANDWIDTH=290400,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=320x180,FRAME-RATE=30.000,CLOSED-CAPTIONS=NONE
master_264.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=635800,AVERAGE-BANDWIDTH=635800,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=426x240,FRAME-RATE=30.000,CLOSED-CAPTIONS=NONE
master_578.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1020800,AVERAGE-BANDWIDTH=1020800,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=30.000,CLOSED-CAPTIONS=NONE
master_928.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1826000,AVERAGE-BANDWIDTH=1826000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=30.000,CLOSED-CAPTIONS=NONE
master_1660.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3696000,AVERAGE-BANDWIDTH=3696000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=30.000,CLOSED-CAPTIONS=NONE
master_3360.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=7326000,AVERAGE-BANDWIDTH=7326000,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=30.000,CLOSED-CAPTIONS=NONE
master_6660.m3u8
```

## Expected Result

What I would expect to see is this (in this case "Recap: Stage 1-3 - Dakar Rally 2018"):
https://appletv.redbull.tv/content/AP-1U6ZA6SE11W11

which maps to a playlist:
https://dms.redbull.tv/v3/AP-1U6ZA6SE11W11/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2IiwiY291bnRyeV9jb2RlIjoiemEiLCJleHBpcmVzIjoiMjAxOC0wMS0xNFQxMzozMToyNS41MzI0MjQxNDNaIiwib3NfZmFtaWx5IjoidHZtbCIsInJlbW90ZV9pcCI6IjU0LjE2Ni4xNjcuMTkwIiwidWEiOiJSdWJ5IiwidWlkIjoiYzVjZDU1NTctYTc4Ni00MTdjLTkyMzctNTkyYmFjNDg4ODBkIn0._IAbo8HyycjMc90UY27Tw9357WML3NLlDOiX6CKSNnA/playlist.m3u8

which contains (notice the full url's):
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-STREAM-INF:BANDWIDTH=7779189,AVERAGE-BANDWIDTH=6533778,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
https://dms.redbull.tv/dms/media/AP-1U6ZA6SE11W11/1920x1080@7779189/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2Iiwib3NfZmFtaWx5IjoidHZtbCIsIm9zX3ZlcnNpb24iOiIiLCJ1aWQiOiJjNWNkNTU1Ny1hNzg2LTQxN2MtOTIzNy01OTJiYWM0ODg4MGQiLCJsYXRpdHVkZSI6MC4wLCJsb25ndGl0dWRlIjowLjAsImNvdW50cnlfaXNvIjoiemEiLCJhZGRyZXNzIjoiNTQuMTY2LjE2Ny4xOTAiLCJpYXQiOjE1MTU1OTEyMTB9.xNqg22Fs9mlcfqC-tocHmTZD4UK_0ADN2pSnPE8L6MQ=/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3935466,AVERAGE-BANDWIDTH=3346327,RESOLUTION=1280x720,CODECS="avc1.4d001f,mp4a.40.2"
https://dms.redbull.tv/dms/media/AP-1U6ZA6SE11W11/1280x720@3935466/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2Iiwib3NfZmFtaWx5IjoidHZtbCIsIm9zX3ZlcnNpb24iOiIiLCJ1aWQiOiJjNWNkNTU1Ny1hNzg2LTQxN2MtOTIzNy01OTJiYWM0ODg4MGQiLCJsYXRpdHVkZSI6MC4wLCJsb25ndGl0dWRlIjowLjAsImNvdW50cnlfaXNvIjoiemEiLCJhZGRyZXNzIjoiNTQuMTY2LjE2Ny4xOTAiLCJpYXQiOjE1MTU1OTEyMTB9.xNqg22Fs9mlcfqC-tocHmTZD4UK_0ADN2pSnPE8L6MQ=/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2755829,AVERAGE-BANDWIDTH=2352288,RESOLUTION=960x540,CODECS="avc1.4d001f,mp4a.40.2"
https://dms.redbull.tv/dms/media/AP-1U6ZA6SE11W11/960x540@2755829/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2Iiwib3NfZmFtaWx5IjoidHZtbCIsIm9zX3ZlcnNpb24iOiIiLCJ1aWQiOiJjNWNkNTU1Ny1hNzg2LTQxN2MtOTIzNy01OTJiYWM0ODg4MGQiLCJsYXRpdHVkZSI6MC4wLCJsb25ndGl0dWRlIjowLjAsImNvdW50cnlfaXNvIjoiemEiLCJhZGRyZXNzIjoiNTQuMTY2LjE2Ny4xOTAiLCJpYXQiOjE1MTU1OTEyMTB9.xNqg22Fs9mlcfqC-tocHmTZD4UK_0ADN2pSnPE8L6MQ=/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1112960,AVERAGE-BANDWIDTH=930373,RESOLUTION=640x360,CODECS="avc1.4d001e,mp4a.40.2"
https://dms.redbull.tv/dms/media/AP-1U6ZA6SE11W11/640x360@1112960/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2Iiwib3NfZmFtaWx5IjoidHZtbCIsIm9zX3ZlcnNpb24iOiIiLCJ1aWQiOiJjNWNkNTU1Ny1hNzg2LTQxN2MtOTIzNy01OTJiYWM0ODg4MGQiLCJsYXRpdHVkZSI6MC4wLCJsb25ndGl0dWRlIjowLjAsImNvdW50cnlfaXNvIjoiemEiLCJhZGRyZXNzIjoiNTQuMTY2LjE2Ny4xOTAiLCJpYXQiOjE1MTU1OTEyMTB9.xNqg22Fs9mlcfqC-tocHmTZD4UK_0ADN2pSnPE8L6MQ=/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=704874,AVERAGE-BANDWIDTH=604115,RESOLUTION=426x240,CODECS="avc1.4d001e,mp4a.40.2"
https://dms.redbull.tv/dms/media/AP-1U6ZA6SE11W11/426x240@704874/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2Iiwib3NfZmFtaWx5IjoidHZtbCIsIm9zX3ZlcnNpb24iOiIiLCJ1aWQiOiJjNWNkNTU1Ny1hNzg2LTQxN2MtOTIzNy01OTJiYWM0ODg4MGQiLCJsYXRpdHVkZSI6MC4wLCJsb25ndGl0dWRlIjowLjAsImNvdW50cnlfaXNvIjoiemEiLCJhZGRyZXNzIjoiNTQuMTY2LjE2Ny4xOTAiLCJpYXQiOjE1MTU1OTEyMTB9.xNqg22Fs9mlcfqC-tocHmTZD4UK_0ADN2pSnPE8L6MQ=/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=331122,AVERAGE-BANDWIDTH=295507,RESOLUTION=320x180,CODECS="avc1.42001e,mp4a.40.2"
https://dms.redbull.tv/dms/media/AP-1U6ZA6SE11W11/320x180@331122/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InNtYXJ0X3R2Iiwib3NfZmFtaWx5IjoidHZtbCIsIm9zX3ZlcnNpb24iOiIiLCJ1aWQiOiJjNWNkNTU1Ny1hNzg2LTQxN2MtOTIzNy01OTJiYWM0ODg4MGQiLCJsYXRpdHVkZSI6MC4wLCJsb25ndGl0dWRlIjowLjAsImNvdW50cnlfaXNvIjoiemEiLCJhZGRyZXNzIjoiNTQuMTY2LjE2Ny4xOTAiLCJpYXQiOjE1MTU1OTEyMTB9.xNqg22Fs9mlcfqC-tocHmTZD4UK_0ADN2pSnPE8L6MQ=/playlist.m3u8
```

## Required Fix:
We'd need to work out a way to find the base url for the playlist file. Unfortunately I don't have much time at the moment, but I'll try look into when I get a gap.

**Comment by andy-g** [comment]
Seems like the call to the playlist actually does a redirect:

```
wget https://dms.redbull.tv/v3/AP-1TQGGWWG91W11/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXRlZ29yeSI6InBlcnNvbmFsX2NvbXB1dGVyIiwiY291bnRyeV9jb2RlIjoidXMiLCJleHBpcmVzIjoiMjAxOC0wMS0xMlQxMzoxODo1OS4wMjgxODA4N1oiLCJvc19mYW1pbHkiOiJodHRwIiwicmVtb3RlX2lwIjoiNTQuMjA1LjcwLjEwNiIsInVhIjoiYXhpb3MvMC4xNy4xIiwidWlkIjoiMGY1N2ExMDktMzM3ZC00OWI0LWE2MWYtYzA3NjBmNTYyODg2In0.xOgpI8ZPaKZdko6suyyQctc9AANK-67jXQdMpsz_HDY/playlist.m3u8 2>&1 | grep Location:
Location: https://rbmh-msl41-test.akamaized.net/hls/live/590971/180110DAKARday04Pri/master.m3u8 [following]
```

so it heads off to:
https://rbmh-msl41-test.akamaized.net/hls/live/590971/180110DAKARday04Pri/master.m3u8
...and then the playlist for each stream quality is actually just a relative link to the current url:
https://rbmh-msl41-test.akamaized.net/hls/live/590971/180110DAKARday04Pri/master_264.m3u8
...which returns a playlist with more relative links to the actual media:
e.g.: https://rbmh-msl41-test.akamaized.net/hls/live/590971/180110DAKARday04Pri/20180110T003252/master_264/00000/master_264_00271.ts
```
#EXTM3U
#EXT-X-ALLOW-CACHE:NO
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:271
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:6,
20180110T003252/master_264/00000/master_264_00271.ts
#EXTINF:6,
20180110T003252/master_264/00000/master_264_00272.ts
#EXTINF:6,
20180110T003252/master_264/00000/master_264_00273.ts
#EXTINF:6,
20180110T003252/master_264/00000/master_264_00274.ts
#EXTINF:6,
20180110T003252/master_264/00000/master_264_00275.ts
#EXTINF:6,
20180110T003252/master_264/00000/master_264_00276.ts
...
...
```

So, it looks like we'd need to check for a redirect in kodi (not sure how easy that'd be to do), and if we don't get a base url for playlists or media, we then need to use the base url that we used to get the original playlist, in this case: https://rbmh-msl41-test.akamaized.net/hls/live/590971/180110DAKARday04Pri

**Comment by zarianu** [comment]
I think that's because they serve Dakar videos from CDN (Akamai) to keep up with the audience demand.

Thank you for your prompt answer and efforts supporting this add-on, hope this issue could be fixed ;)

**Comment by andy-g** [comment]
I've actually started trying to move it off the appletv api, and onto the standard api, as there were some issues with page limits and not being able to page to the next page in long lists (#6). My start is here (#7)  but I ran into some issues with artwork not loading (may ahve something to do with chgunking and missing content-length header), but in essence it's needing a bit of extra time.

I'll have to decide which is best to prioritise, may try wrap up the API migration, and then do this fix once that's merged in.

**Comment by andy-g** [comment]
@zarianu My change request has been merged into the Kodi add-on repository, but it can take a little while to reflect. Keep checking for updates & when it updates to version 2.0.2 please test the dakar stream that was giving you issues.

**Comment by andy-g** [comment]
@zarianu Closing this as the update is now available on the official add-on repo and the streams that were previously failing are now resolved.

**Comment by zarianu** [comment]
@andy-g just tested it - yeah, problem streams are playing like a charm now, thank you for your efforts!
